package installengine

import (
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
)

func ReadEnvFile(path string) (map[string]string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return ParseEnvContents(string(contents))
}

func ParseEnvContents(contents string) (map[string]string, error) {
	values := make(map[string]string)
	for lineNumber, rawLine := range strings.Split(contents, "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return nil, fmt.Errorf("invalid config.env line %d", lineNumber+1)
		}
		values[key] = strings.Trim(value, " \t")
	}
	return values, nil
}
func ValidEnvKey(value string) bool {
	if value == "" {
		return false
	}
	for index, character := range value {
		if (character < 'A' || character > 'Z') && (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '_' {
			return false
		}
		if index == 0 && character >= '0' && character <= '9' {
			return false
		}
	}
	return true
}
func FormatEnvFile(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by Stealth. Keep this file private.\n")
	for _, key := range keys {
		builder.WriteString(key)
		builder.WriteByte('=')
		builder.WriteString(values[key])
		builder.WriteByte('\n')
	}
	return builder.String()
}
func MergeEnv(base map[string]string, updates map[string]string) (string, error) {
	values := make(map[string]string, len(base)+len(updates))
	for key, value := range base {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	for key, value := range updates {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	return FormatEnvFile(values), nil
}
func PortOrDefault(raw, fallback string) string {
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || value < 1 || value > 65535 {
		return fallback
	}
	return strconv.Itoa(value)
}
