package installengine

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/Stealth-deplover/stealth/internal/buildkitpki"
)

// Layout is the on-host installation boundary. The host CLI writes durable
// production files and runs Compose from this root; the setup API only shares
// the separate encrypted state directory.
type Layout struct {
	Root                string
	EnvFile             string
	ComposeFile         string
	SetupComposeFile    string
	TelemetryDir        string
	ProxyFile           string
	TraefikDir          string
	TraefikStatic       string
	TraefikDynamic      string
	TraefikCore         string
	TraefikGenerated    string
	TraefikReloadMarker string
	VersionFile         string
	StateDir            string
	PrivateDir          string
	BuildKitPKIDir      string
}

func NewLayout(root string) (Layout, error) {
	root = strings.TrimSpace(root)
	if root == "" {
		return Layout{}, errors.New("installation root is required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve installation root: %w", err)
	}
	clean := filepath.Clean(abs)
	if clean == string(filepath.Separator) {
		return Layout{}, errors.New("refusing filesystem root as installation root")
	}
	return Layout{
		Root:                clean,
		EnvFile:             filepath.Join(clean, "config.env"),
		ComposeFile:         filepath.Join(clean, "compose.production.yaml"),
		SetupComposeFile:    filepath.Join(clean, "compose.setup.yaml"),
		TelemetryDir:        filepath.Join(clean, "telemetry"),
		ProxyFile:           filepath.Join(clean, "console", "deploy", "nginx.conf"),
		TraefikDir:          filepath.Join(clean, "traefik"),
		TraefikStatic:       filepath.Join(clean, "traefik", "traefik.yaml"),
		TraefikDynamic:      filepath.Join(clean, "traefik", "dynamic"),
		TraefikCore:         filepath.Join(clean, "traefik", "dynamic", "core.yaml"),
		TraefikGenerated:    filepath.Join(clean, "traefik", "dynamic", "generated"),
		TraefikReloadMarker: filepath.Join(clean, "traefik", "dynamic", ".reload.yaml"),
		VersionFile:         filepath.Join(clean, "VERSION"),
		StateDir:            filepath.Join(clean, "state"),
		PrivateDir:          filepath.Join(clean, "private"),
		BuildKitPKIDir:      filepath.Join(clean, "private", buildkitpki.DirectoryName),
	}, nil
}

// Plan contains only installation decisions. Secrets are generated by the
// engine for a fresh plan or are supplied as already-rendered ConfigContents
// for a browser-confirmed plan.
type Plan struct {
	Layout  Layout
	Version string
	// CLIVersion identifies the host binary that requested a platform rollback.
	// The doctor command uses the resulting rollback state to distinguish the
	// intentional platform/CLI version skew from a failed self-update.
	CLIVersion string
	// InstalledVersion is the release currently recorded by an existing
	// installation. Version is the target release for this operation. Keeping
	// both values lets managed configuration advance canonical image references
	// without overwriting operator-selected image overrides.
	InstalledVersion   string
	PublicURL          string
	GitHubAppClientID  string
	DockerGID          uint32
	Existing           bool
	Setup              bool
	ExternalDatabase   bool
	ExternalRedis      bool
	Cloudflare         bool
	VerifyPublicURL    bool
	IngressNetworkName string
	ConfigContents     string
	InternalAPIURL     string
	InternalConsoleURL string
	InternalProxyURL   string
}
type Step int

const (
	StepConfiguration Step = iota
	StepPull
	StepDependencies
	StepMigration
	StepServices
	StepVerify
)

var StepNames = []string{
	"Configuration and secrets",
	"Release images",
	"PostgreSQL and Redis",
	"Database migrations",
	"API, Worker, BuildKit, Console, Proxy, and Traefik",
	"Health and readiness verification",
}

type Event struct {
	Step    string    `json:"step"`
	Status  string    `json:"status"`
	Message string    `json:"message,omitempty"`
	Error   string    `json:"error,omitempty"`
	At      time.Time `json:"at"`
}
